### ISSUE TITLE
Adding @Context in @AfterMapping or @BeforeMapping is not working

### ISSUE THREAD

**Issue by rajadilipkolli** [mapstruct/mapstruct-spring-extensions#62]
When Integrating with `@Context` in `@AfterMapping` or `@BeforeMapping` is not working 

Below Example is working as expected,

```
@Mapper(
        config = MapperSpringConfig.class,
        builder = @Builder(disableBuilder = true),
        uses = EntityManager.class)
public interface NewPostRequestToPostEntityMapper extends Converter<NewPostRequest, PostEntity> {

    @Mapping(target = "tags", ignore = true)
    PostEntity convert(NewPostRequest newPostRequest);

    @AfterMapping
    default void afterMapping(NewPostRequest newPostRequest, @MappingTarget PostEntity postEntity) {
        newPostRequest
                .tags()
                .forEach(tagsRequest -> postEntity.addTag(getTagEntity(null, tagsRequest)));
    }
}
```

But the moment I add `@Context EntityManager entityManager` as third parameter afterMapping method is not generating. I expect it to be working like normal Mapstruct.

```java
@Mapper(
        config = MapperSpringConfig.class,
        builder = @Builder(disableBuilder = true),
        uses = EntityManager.class)
public interface NewPostRequestToPostEntityMapper extends Converter<NewPostRequest, PostEntity> {

    @Mapping(target = "tags", ignore = true)
    PostEntity convert(NewPostRequest newPostRequest);

    @AfterMapping
    default void afterMapping(
            NewPostRequest newPostRequest,
            @MappingTarget PostEntity postEntity,
            @Context EntityManager entityManager) {
        newPostRequest
                .tags()
                .forEach(
                        tagsRequest -> postEntity.addTag(getTagEntity(entityManager, tagsRequest)));
    }
}
```

Sample code can be found [here](https://github.com/rajadilipkolli/my-spring-boot-experiments/tree/main/graphql/spring-boot-graphql-webmvc) to reproduce the issue

**Comment by Chessray** [comment]
@filiphr This feels like it should be an issue in Mapstruct Core rather than the extension, doesn't it?

**Comment by Chessray** [comment]
OK, so I've had some more time to look at this now:

1. This is not how the `@Context` mechanism is supposed to work. In order to pass `@Context` parameters into e.g. the `@AfterMapping` method like in your example, they must already be passed in as `@Context` into the main mapping method.
2. This isn't Spring-specific and especially hasn't got anything to do with the extension. It's just how MapStruct works.

From your example, I suppose what you're trying to achieve is that the generated code somehow figures out on its own that it has to call the EntityManagerFactory in order to obtain the EntityManager. MapStruct isn't that smart. You'll have to inject it explicitly and then use it in your `@AfterMapping` method.

**Comment by rajadilipkolli** [comment]
Hi @Chessray,

I have updated my sample to set `@Context` to the convert method defined

Update Code:

```java

@Mapper(
        config = MapperSpringConfig.class,
        builder = @Builder(disableBuilder = true),
        uses = {TagRepository.class})
public interface NewPostRequestToPostEntityMapper extends Converter<NewPostRequest, PostEntity> {

    @Mapping(target = "tags", ignore = true)
    @Mapping(
            target = "publishedAt",
            expression = "java(newPostRequest.published() ? java.time.LocalDateTime.now() : null)")
    PostEntity convert(NewPostRequest newPostRequest, @Context TagRepository tagRepository);
```

This code is generating two methods one with injected `@Context` and without it like below.

```java
@Component
public class NewPostRequestToPostEntityMapperImpl implements NewPostRequestToPostEntityMapper {

    @Override
    public PostEntity convert(NewPostRequest source) {
               ------------------
    }
     
    ---------------
``` 

and

```java
    @Override
    public PostEntity convert(NewPostRequest newPostRequest, TagRepository tagRepository) {
          --------------
          afterMapping( newPostRequest, postEntity, tagRepository );
   }
```

Is it possible to generate only one method the one with injected `@Context` and convensationService can call this?

Alternative Solution:

Deviating from spring extension and injecting directly like 
`private final NewPostRequestToPostEntityMapper mapNewPostRequestToPostEntityMapper;`  helps me to call the 


```java
 PostEntity postEntity =
                this.mapNewPostRequestToPostEntityMapper.convert(newPostRequest, tagRepository);
```

I am looking at solution where I can call

```java
PostEntity postEntity =
                this.conversionServiceAdapter.mapNewPostRequestToPostEntity(newPostRequest, tagRepository);
```

How to resolve this?

**Comment by Chessray** [comment]
1. One shouldn't usually call the generated Adapter class from the outside. It's intended to be used inside Mappers in order to facilitate loose coupling. The whole idea of this extension is to enable you to use Spring's built-in ConversionService with MapStruct mappers.
2. The reason why your design generates two methods is that Spring's definition of a `Converter` is very strict and doesn't allow for something like `@Context` parameters. So the MapStruct core generator "sees" two mapping method declarations (one from the base interface and the other one that you defined yourself) and generates accordingly.
3. However, the adapter class generator only cares about the one following Spring's convention, because that's its intended use.
4. It comes down to an either-or choice:
    - If you want to follow Spring's `Converter` model, you have to live without `@Context` objects. Spring's strict definition of the [Converter](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/convert/converter/Converter.html) interface simply doesn't allow them. So you must either inject the objects or somehow add them to the source type.
    - If you really want to keep the `@Context` objects, then that particular Mapper can't extend the `Converter` interface, because the method signatures are incompatible. It's perfectly valid for a Mapper to stand on its own and not extend `Converter`. The downside is that in this case, you can't register it with the `ConversionService` either.

The choice is yours.

**Comment by rajadilipkolli** [comment]
Thanks for the detailed clarification @Chessray
