### ISSUE TITLE
spring-beans vulnerability CVE-2022-22965

### ISSUE THREAD

**Issue by giorgioscia** [mapstruct/mapstruct-spring-extensions#97]
Hi there,

Unable to use test-extensions within my org as it has dependency on vulnerable version of spring-beans CVE-2022-22965. Is there any plan to upgrade in the near future?

Many thanks! :)

[1] [SNYK-JAVA-ORGSPRINGFRAMEWORK-2436751](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-2436751)
[2] [CVE-2022-22965](https://www.cve.org/CVERecord?id=CVE-2022-22965)

**Comment by Chessray** [comment]
There should be no risk of this vulnerability affecting your project as this is merely a testing support library. The dependencies are consciously kept on a low minimum version in order to allow maximum compatibility. My best suggestion is that you try to adjust the project configuration so that the transitive dependency gets replaced by a different one or find a way within your organization to allow this for testing purposes.

**Comment by giorgioscia** [comment]
Unfortunately to use an external artifact within the org, it has to go through automated sign-off and it's failing due to the vulnerability

**Comment by Chessray** [comment]
In that case, why don't you just copy the code into your own repo and use a later Spring version as dependency? The test extensions module is very small and unlikely to receive many changes over the years, so should be easy enough to maintain.
